### ISSUE TITLE
Error After Install

### ISSUE THREAD

**Issue by treebeard9** [Umoxfo/brackets-w3cvalidation#3]
Console error

ErrorNotification.js:122 [NodeDomain] Error loading domain "nu.validator": Unable to load one of the modules: /Users/myusernamehere/Library/Application Support/Brackets/extensions/user/umoxfo.w3cvalidation/node/ValidationServer, reason: Cannot find module 'util.promisify'

**Comment by Umoxfo** [comment]
This problem is due to lack of the node library.
So, I will replace with the new file.
