### ISSUE TITLE
Cannot install on Brackets Mac - invalid ZIP

### ISSUE THREAD

**Issue by abtechteacher** [Umoxfo/brackets-w3cvalidation#4]
Installing through Extensions Manager - get "invalid zip" error. I am a teacher. Three of my students - all using Macs - have reported this. No Windows users have reported it. Is there an issue with this extension and Macs?

**Comment by Umoxfo** [comment]
I cannot say anything because I have not received such a report so far.

**Comment by cyberwisdom** [comment]
I received the same error when trying to install the extension today on Mac OS High Sierra.  See attached screenshots. 

Brackets Version:
```
Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
build timestamp: Wed Sep 20 2017 03:34:28 GMT-0700
```

<img width="682" alt="screen shot 2018-01-19 at 1 52 23 pm" src="https://user-images.githubusercontent.com/6466470/35166514-20d03348-fd20-11e7-89ab-11dfbd8eb165.png">
<img width="722" alt="screen shot 2018-01-19 at 1 52 30 pm" src="https://user-images.githubusercontent.com/6466470/35166515-20e29588-fd20-11e7-943b-e7045e50d3e8.png">

**Comment by Umoxfo** [comment]
I released new version that changed compression method.

**Comment by cyberwisdom** [comment]
New version installs fine now.  Thanks!
