### ISSUE TITLE
nu.validator timeouts

### ISSUE THREAD

**Issue by abtechteacher** [Umoxfo/brackets-w3cvalidation#5]
Won't validate anything. Panel at the bottom just says:
**nu.validator has timed out after waiting for 10000 ms**
Displays this on page load and never changes. Save the page - won't validate. Choose Edit > Refresh W3 Validate - won't validate. Tap [F9] - won't validate. Just displays the same nu.validator error. 

This extension used to work beautifully. Something must have happened in the last few builds (like the compression method that caused "invalid zip" errors for Mac users trying to install.)

**Comment by Umoxfo** [comment]
Sorry, this extension takes time to work.

I am working to prevent errors during internal processing.

**Comment by francwalter** [comment]
On a fresh brackets installation on Windows 8.1 (64) I have this error too.
It wont validate at all since I installed that plugin.
Why is the issue closed?

**Comment by Umoxfo** [comment]
I fixed this issue with v1.1.0.

Please refer to README.md for updating to v1.1.0
