### ISSUE TITLE
Marked for removal but it does not uninstall

### ISSUE THREAD

**Issue by salr** [Umoxfo/brackets-w3cvalidation#6]
It will not uninstall.  For this feature to work, I would have had to let it comm through the firewall. I chose not to, and it timed out with an error message, which is understandable given that I did not allow comm through the firewall.

I decided to uninstall and marked it for removal through the extension manager.

The uninstall does not work. Multiple attempts with same results after rebooting etc.  Does the uninstall require communication through the firewall?  I don't see why it should, but if it does, that explains why it will not work.

How do I manually uninstall?

**Comment by Umoxfo** [comment]
This extension uses [the Nu Html Checker](https://github.com/validator/validator), and the library is downloaded to the first startup after installed the extension.

Manual uninstall
1. Open Extension folder (Help > Show Extensions Folder)
1. Close Brackets
1. Open the 'user" folder
![extentions](https://user-images.githubusercontent.com/5876745/35473761-a3f511fc-0339-11e8-8fe8-d86ae5edb680.PNG)
1. Delete the "umoxfo.w3cvalidation" folder
