### ISSUE TITLE
Failed to install from Brackets

### ISSUE THREAD

**Issue by design-dreams** [Umoxfo/brackets-w3cvalidation#9]
I tried to install this from Brackets. I have never installed it before. It said "Installation Failed - The downloaded content is not a valid zip file."

**Comment by schroef** [comment]
I got same error on OSX

**Comment by CharlesJS** [comment]
+1, fails to install on macOS.

**Comment by Umoxfo** [comment]
Sorry, I replaced a package.

Same cause as issue #4.

**Comment by schroef** [comment]
It installs, after search i see a menu item in the edit menu. Press F9. Nothing happens on php pages which are full html.

Where is your info about this addon, there is nothing? Just how to install it?

**Comment by CharlesJS** [comment]
Thanks Umoxfo, the new package seems to work now.

**Comment by Umoxfo** [comment]
@schroef 
After installation, it takes some time for this extension to work.
In addition, ONLY html files are supported.

**Comment by Umoxfo** [comment]
#4
